project:
  type: website
  output-dir: docs

website:
  title: "Restaurant Ebook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: summary.qmd
        text: Summary
      - href: references.qmd
        text: References

format:
  html:
    theme: cosmo
    toc: true


